CREATE TABLE IF NOT EXISTS customers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    f_name TEXT NOT NULL,
    l_name TEXT NOT NULL,
    email TEXT UNIQUE,
    phone INTEGER,
    vat INTEGER
);

CREATE TABLE IF NOT EXISTS products (
    sku INTEGER,
    product_name TEXT NOT NULL,
    price REAL,
    PRIMARY KEY (sku)
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    passw TEXT NOT NULL
);
